# Generated by Django 5.0.6 on 2024-07-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='placed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='placed_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='betcodes.comment'),
        ),
    ]
