# Generated by Django 5.0.6 on 2024-07-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betcodes', '0002_rename_placed_at_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
