# Generated by Django 5.0.6 on 2024-07-28 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcodes', '0002_competition_continent_country_footballteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='country',
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='betcodes.country')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='betcodes.association'),
        ),
    ]
