# Generated by Django 5.0.6 on 2024-09-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcodes', '0003_remove_competition_continent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betcode',
            name='competiton',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
