# Generated by Django 5.0.6 on 2024-09-16 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betcodes', '0004_betcode_competiton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betcode',
            old_name='competiton',
            new_name='competition',
        ),
    ]
